// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dppjfqblgeocraduavor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwcGpmcWJsZ2VvY3JhZHVhdm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1Njg0NzYsImV4cCI6MjA2MzE0NDQ3Nn0.9sl-7-EAxdNSp3tuSxBtXp7EPTqpK2ItOWGBFyyeh0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);