// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pslqsgyeigurogztbqzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbHFzZ3llaWd1cm9nenRicXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjY4NDcsImV4cCI6MjA2MjgwMjg0N30.ssODFNw2DJf_XON3or7d99t5J0lhO7zAxbJn1mMEh60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);